/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

import javax.swing.JOptionPane;



import java.awt.EventQueue;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.util.Date;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextArea;
import java.io.*;




/**
 *
 * @author MSii
 */
public class Complain extends javax.swing.JFrame {

    /**
     * Creates new form Complain
     */
    public Complain() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(190, 168, 149));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_enter_complain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmsg = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtsub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\customer\\gif_coffee.gif")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_enter_complain.setBackground(new java.awt.Color(255, 224, 212));
        btn_enter_complain.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_enter_complain.setForeground(new java.awt.Color(95, 0, 0));
        btn_enter_complain.setText("Send");
        btn_enter_complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enter_complainActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enter_complain, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, 90, 30));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plase contact 0771477627(manager)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 320, -1));

        txtmsg.setColumns(20);
        txtmsg.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtmsg.setRows(5);
        jScrollPane1.setViewportView(txtmsg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\customer\\gif_coffee.gif")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 460, 350));

        txtEmail.setEditable(false);
        txtEmail.setText("harshanimanisha2@gmail.com");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, -1));

        txtsub.setEditable(false);
        txtsub.setText("Complain");
        getContentPane().add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("complain");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\update customer\\img_cup_cake.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 590, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public void sendmail()
	{
		 String to = "hashini.mahinsa.fernando@gmail.com";
	      String from = "hashini.mahinsa.fernando@gmail.com";
	      String host = "localhost";
	      String port = "25";
	  
	      final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
	 
	         Properties props = System.getProperties();
	         props.setProperty("mail.smtp.host", "smtp.gmail.com");
	         props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
	         props.setProperty("mail.smtp.socketFactory.fallback", "false");
	         props.setProperty("mail.smtp.port", "465");
	         props.setProperty("mail.smtp.socketFactory.port", "465");
	         props.put("mail.smtp.auth", "true");
	         props.put("mail.debug", "true");
	         props.put("mail.store.protocol", "pop3");
	         props.put("mail.transport.protocol", "smtp");
	         final String username = "hashini.mahinsa.fernando@gmail.com";//
	         final String password = "MissRawathawa11@";
	         try{
	         Session session = Session.getInstance(props, 
	                              new Authenticator(){
                                         @Override
	                                 protected PasswordAuthentication getPasswordAuthentication() {
	                                    return new PasswordAuthentication(username, password);
	                                 }});
	     
	         Message msg = new MimeMessage(session);

	   
	         msg.setFrom(new InternetAddress(txtEmail.getText()));
	         msg.setRecipients(Message.RecipientType.TO, 
	                          InternetAddress.parse(txtEmail.getText(),false));
	         msg.setSubject(txtsub.getText());
	         msg.setText(txtmsg.getText());
	         
	         
	         
	        
	         
	         msg.setSentDate(new Date());
	         Transport.send(msg);
	         JOptionPane.showMessageDialog(null, "Sent");
	      }catch (MessagingException e){ System.out.println("Erreur d'envoi, cause: " + e);}
	   }  
    
    
    
    
    
    private void btn_enter_complainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enter_complainActionPerformed
       
       
        /*email, must include customer deatails also!
          or
         quaries*/
        
        sendmail();
        
        this.dispose();
        
        JOptionPane.showMessageDialog(this, "e mail sent to manager","Complain", JOptionPane.INFORMATION_MESSAGE); 
        
    }//GEN-LAST:event_btn_enter_complainActionPerformed

    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Complain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter_complain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtmsg;
    private javax.swing.JTextField txtsub;
    // End of variables declaration//GEN-END:variables
}
