/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

import hevenly.Database.DatabaseConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MSii
 */
public class CustomerTableNumber extends javax.swing.JFrame {

    /**
     * Creates new form CustomerTableNumber
     */
    public CustomerTableNumber() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(190, 168, 149));
        
        lbl_table_number.setVisible(false);
        combo_table_number.setVisible(false);
        btn_table_number_enter.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_choose = new javax.swing.ButtonGroup();
        lbl_table_number = new javax.swing.JLabel();
        btn_table_number_enter = new javax.swing.JButton();
        txt_table_number = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_table_number = new javax.swing.JComboBox<>();
        btn_select_a_table = new javax.swing.JButton();
        txt_bill_id = new javax.swing.JTextField();
        txt_order_type = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_reservation_fee = new javax.swing.JTextField();
        btn_change_service = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_table_number.setBackground(new java.awt.Color(192, 168, 149));
        lbl_table_number.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        lbl_table_number.setForeground(new java.awt.Color(255, 255, 255));
        lbl_table_number.setText("Table number");
        getContentPane().add(lbl_table_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 130, -1));

        btn_table_number_enter.setBackground(new java.awt.Color(255, 224, 212));
        btn_table_number_enter.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_table_number_enter.setForeground(new java.awt.Color(95, 0, 0));
        btn_table_number_enter.setText("Enter");
        btn_table_number_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_table_number_enterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_table_number_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 80, 30));

        txt_table_number.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\customer\\gif_coffee.gif")); // NOI18N
        getContentPane().add(txt_table_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 510, 390));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 510, -1, -1));

        combo_table_number.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        combo_table_number.setForeground(new java.awt.Color(95, 0, 0));
        combo_table_number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        getContentPane().add(combo_table_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, 30));

        btn_select_a_table.setBackground(new java.awt.Color(255, 224, 212));
        btn_select_a_table.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        btn_select_a_table.setForeground(new java.awt.Color(95, 0, 0));
        btn_select_a_table.setText("Select a table");
        btn_select_a_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select_a_tableActionPerformed(evt);
            }
        });
        getContentPane().add(btn_select_a_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, 60));

        txt_bill_id.setEditable(false);
        getContentPane().add(txt_bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        txt_order_type.setEditable(false);
        getContentPane().add(txt_order_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel1.setText("Bill id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 20));

        jLabel2.setText("order type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jLabel4.setText("reservation fee Rs");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, -1, -1));

        txt_reservation_fee.setEditable(false);
        getContentPane().add(txt_reservation_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 150, -1, -1));

        btn_change_service.setBackground(new java.awt.Color(190, 168, 149));
        btn_change_service.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_change_service.setForeground(new java.awt.Color(95, 0, 0));
        btn_change_service.setText("change service");
        btn_change_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_serviceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_change_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\update customer\\img_cup_cake.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 590, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        int table = 0;
        String table_no ="";
        String selected_table_no = "";
        int selected_table=0;
    
    private void btn_table_number_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_table_number_enterActionPerformed
        if(combo_table_number.getSelectedItem()=="select")
        {
         JOptionPane.showMessageDialog(this, "please enter table number first","table selection", JOptionPane.ERROR_MESSAGE); 
        }

        else{
        selected_table_no = (String) combo_table_number.getSelectedItem();
        
        con = DatabaseConnector.connect();
        
        try{
        String q = "update customertable set status='unavailable' where table_no='"+selected_table_no+"'";
        pst  = con.prepareStatement(q);
        pst.execute();
        
        JOptionPane.showMessageDialog(this, "your order will be served at table"+selected_table_no ,"customer registration", JOptionPane.INFORMATION_MESSAGE); 
        Order n = new Order();
        n.txt_bill_id.setText(txt_bill_id.getText());
        n.txt_order_type.setText(txt_order_type.getText());
        n.txt_reservation_fee.setText(txt_reservation_fee.getText());     
        n.txt_location.setText((String)combo_table_number.getSelectedItem());
        n.setVisible(true);
        this.dispose();
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error","table selection", JOptionPane.ERROR_MESSAGE); 
        }
   
        }
    }//GEN-LAST:event_btn_table_number_enterActionPerformed

    private void btn_select_a_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select_a_tableActionPerformed
        con = DatabaseConnector.connect();
        
        try{
        String q = "select table_no from customertable where status='available'";
        pst  = con.prepareStatement(q);
        rs = pst.executeQuery();
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error","table selection", JOptionPane.ERROR_MESSAGE); 
        }

        try{
        while(rs.next())
       {
        int table = rs.getInt("table_no");
        String table_no = String.valueOf( table );
        combo_table_number.addItem(table_no);
       }
        }
        catch(Exception e){}
        
        lbl_table_number.setVisible(true);
        combo_table_number.setVisible(true);
        btn_table_number_enter.setVisible(true);
        btn_select_a_table.setVisible(false);
    }//GEN-LAST:event_btn_select_a_tableActionPerformed

    private void btn_change_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_serviceActionPerformed
       Customer a3 = new Customer(txt_bill_id.getText());
       a3.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_change_serviceActionPerformed

     public int getselected_table_no(){
         selected_table= Integer.parseInt(selected_table_no);
         return selected_table;   
         }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerTableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerTableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerTableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerTableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerTableNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change_service;
    private javax.swing.JButton btn_select_a_table;
    private javax.swing.JButton btn_table_number_enter;
    private javax.swing.JComboBox<String> combo_table_number;
    private javax.swing.ButtonGroup grp_choose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_table_number;
    public javax.swing.JTextField txt_bill_id;
    public javax.swing.JTextField txt_order_type;
    public javax.swing.JTextField txt_reservation_fee;
    private javax.swing.JLabel txt_table_number;
    // End of variables declaration//GEN-END:variables
}
