/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

import static hevenly.CustermerRegistration.isValidPhone;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import hevenly.Database.DatabaseConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;


/**
 *
 * @author MSii
 */
public class CustermerSignIn extends javax.swing.JFrame {

    /**
     * Creates new form CustermerSignIn
     */
    public CustermerSignIn() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_customer_sign_in = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_customer_username = new javax.swing.JTextField();
        btn_log_out_from_sign_in = new javax.swing.JButton();
        btn_customer_registration_from_customer_sign_in = new javax.swing.JButton();
        txt_bill_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_customer_sign_in.setBackground(new java.awt.Color(190, 168, 152));
        btn_customer_sign_in.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_customer_sign_in.setForeground(new java.awt.Color(78, 0, 0));
        btn_customer_sign_in.setText("Log In");
        btn_customer_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_sign_inActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customer_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 150, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        txt_customer_username.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        getContentPane().add(txt_customer_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 150, 30));

        btn_log_out_from_sign_in.setBackground(new java.awt.Color(255, 224, 212));
        btn_log_out_from_sign_in.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_log_out_from_sign_in.setForeground(new java.awt.Color(95, 0, 0));
        btn_log_out_from_sign_in.setText("Log out");
        btn_log_out_from_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_out_from_sign_inActionPerformed(evt);
            }
        });
        getContentPane().add(btn_log_out_from_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 30, 100, 30));

        btn_customer_registration_from_customer_sign_in.setBackground(new java.awt.Color(255, 224, 212));
        btn_customer_registration_from_customer_sign_in.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_customer_registration_from_customer_sign_in.setForeground(new java.awt.Color(95, 0, 0));
        btn_customer_registration_from_customer_sign_in.setText("new? create customer account first!");
        btn_customer_registration_from_customer_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_registration_from_customer_sign_inActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customer_registration_from_customer_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, 30));
        getContentPane().add(txt_bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\login\\img_custermer.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
       Connection con = null;
       PreparedStatement pst = null;
       ResultSet rs = null;
       
       
    
    private void forCreateCustomerAccount(){
       CustermerRegistration w = new CustermerRegistration();
       w.setVisible(true);
       this.dispose();
    }
 
    private void btn_customer_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_sign_inActionPerformed

        if("".equals(txt_customer_username.getText()))
        {
           JOptionPane.showMessageDialog(this, "please enter user name, if haven't account create one!","customer sign in", JOptionPane.ERROR_MESSAGE); 
           
           
           int response3 = JOptionPane.showConfirmDialog(this,"Do you want create a customer account?" , "customer registration",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
           if(response3==JOptionPane.YES_OPTION)
           { 
              this.dispose();
              forCreateCustomerAccount();
           }
        
           else if(response3==JOptionPane.NO_OPTION)
           {
              this.setVisible(true);
              txt_customer_username.setText("");  
           }
        }
        
        else if(isValidPhone(txt_customer_username.getText()) == false)
        {
            JOptionPane.showMessageDialog(this, "Enter valid user name, if haven't account create one!","customer registration", JOptionPane.ERROR_MESSAGE); 
            int response2 = JOptionPane.showConfirmDialog(this,"Do you want create a customer account?" , "customer registration",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
            if(response2==JOptionPane.YES_OPTION)
            { 
              this.dispose();
              forCreateCustomerAccount();
            }
        
            else if(response2==JOptionPane.NO_OPTION)
            {
              this.setVisible(true);
              txt_customer_username.setText("");  
            }

        }
        
        else{
            con = DatabaseConnector.connect();
        
            try{
              String q = "select c_TP from customer where c_TP='"+txt_customer_username.getText()+"'";
              pst  = con.prepareStatement(q);
              rs = pst.executeQuery();
            }
        
            catch(Exception e){
              JOptionPane.showMessageDialog(this, "Error","customer sign in", JOptionPane.ERROR_MESSAGE); 
              int response3 = JOptionPane.showConfirmDialog(this,"Do you want create a customer account?" , "customer sign in",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
              if(response3==JOptionPane.YES_OPTION)
              { 
                this.dispose();
                forCreateCustomerAccount();
              }
        
              else if(response3==JOptionPane.NO_OPTION)
              {
                Start u = new Start();
                u.setVisible(true);
                this.dispose();
              }
        }
        
        try{
            String q = "insert into bill (c_TP) values ('"+txt_customer_username.getText()+"')";
            pst  = con.prepareStatement(q);
            pst.execute();
            
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error","customer sign in", JOptionPane.ERROR_MESSAGE); 
        
            int response = JOptionPane.showConfirmDialog(this,"Do you want to log out?" , "customer sign in",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
            if(response==JOptionPane.YES_OPTION)
              { 
                this.dispose();
                Start a1= new Start();
                a1.setVisible(true);
              }
        
            else if(response==JOptionPane.NO_OPTION)
             {
                
              
             }
        }
  
        try{
        String q = "select bill_id from bill where c_TP='"+txt_customer_username.getText()+"' order by bill_id";
        pst  = con.prepareStatement(q);
        rs = pst.executeQuery();
        String a = "";
        while (rs.next()) {
            a=rs.getString(1);
            
        }
        txt_bill_id.setText(a);
        Customer a3 = new Customer(txt_bill_id.getText());
        a3.setVisible(true);
        this.dispose();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error","order", JOptionPane.ERROR_MESSAGE); 
        
        int response = JOptionPane.showConfirmDialog(this,"Do you want to log out?" , "order",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
            if(response==JOptionPane.YES_OPTION)
            { 
              this.dispose();
              Start a1= new Start();
              a1.setVisible(true);
            }
        
            else if(response==JOptionPane.NO_OPTION)
            {
  
            }
            
        }  
   
        }  

    }//GEN-LAST:event_btn_customer_sign_inActionPerformed

    
    private void btn_log_out_from_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_out_from_sign_inActionPerformed
        
        Start t = new Start();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_log_out_from_sign_inActionPerformed

    private void btn_customer_registration_from_customer_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_registration_from_customer_sign_inActionPerformed
        forCreateCustomerAccount();
    }//GEN-LAST:event_btn_customer_registration_from_customer_sign_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustermerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustermerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustermerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustermerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustermerSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_customer_registration_from_customer_sign_in;
    private javax.swing.JButton btn_customer_sign_in;
    private javax.swing.JButton btn_log_out_from_sign_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_bill_id;
    private javax.swing.JTextField txt_customer_username;
    // End of variables declaration//GEN-END:variables
}
