/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

import javax.swing.JOptionPane;

/**
 *
 * @author MSii
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */

    public Customer(String a) {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(190, 168, 149));
        
        txt_bill_id.setText(a);
   
    }

    private Customer() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_drive_thru_service = new javax.swing.JButton();
        btn_dine_in = new javax.swing.JButton();
        btn_update_customer = new javax.swing.JButton();
        btn_customer_log_out_from_main = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        redio_btn_dine_in = new javax.swing.JLabel();
        btn_take_away = new javax.swing.JButton();
        btn_reservations = new javax.swing.JButton();
        txt_bill_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_drive_thru_service.setBackground(new java.awt.Color(255, 224, 212));
        btn_drive_thru_service.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        btn_drive_thru_service.setForeground(new java.awt.Color(95, 0, 0));
        btn_drive_thru_service.setText("Drive thru");
        btn_drive_thru_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_drive_thru_serviceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_drive_thru_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 210, 130));

        btn_dine_in.setBackground(new java.awt.Color(255, 224, 212));
        btn_dine_in.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        btn_dine_in.setForeground(new java.awt.Color(95, 0, 0));
        btn_dine_in.setText("Dine in");
        btn_dine_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dine_inActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dine_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 210, 130));

        btn_update_customer.setBackground(new java.awt.Color(192, 168, 149));
        btn_update_customer.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_update_customer.setForeground(new java.awt.Color(255, 255, 255));
        btn_update_customer.setText("edit my profile");
        btn_update_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_customerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 25, -1, -1));

        btn_customer_log_out_from_main.setBackground(new java.awt.Color(192, 168, 149));
        btn_customer_log_out_from_main.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_customer_log_out_from_main.setForeground(new java.awt.Color(255, 255, 255));
        btn_customer_log_out_from_main.setText("Logout");
        btn_customer_log_out_from_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_log_out_from_mainActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customer_log_out_from_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));

        redio_btn_dine_in.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\customer\\gif_coffee.gif")); // NOI18N
        getContentPane().add(redio_btn_dine_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 440));

        btn_take_away.setBackground(new java.awt.Color(255, 224, 212));
        btn_take_away.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        btn_take_away.setForeground(new java.awt.Color(95, 0, 0));
        btn_take_away.setText("Take away");
        btn_take_away.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_take_awayActionPerformed(evt);
            }
        });
        getContentPane().add(btn_take_away, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 210, 130));

        btn_reservations.setBackground(new java.awt.Color(255, 224, 212));
        btn_reservations.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        btn_reservations.setForeground(new java.awt.Color(95, 0, 0));
        btn_reservations.setText("reservations");
        btn_reservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservationsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 210, 130));

        txt_bill_id.setEditable(false);
        getContentPane().add(txt_bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 90, 30));

        jLabel1.setText("bill id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\update customer\\img_cup_cake.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 590, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btn_customer_log_out_from_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_log_out_from_mainActionPerformed
        
        Start k = new Start();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_customer_log_out_from_mainActionPerformed

    private void btn_update_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_customerActionPerformed
        
        UpdateCustomer l = new UpdateCustomer();
        l.setVisible(true);
    }//GEN-LAST:event_btn_update_customerActionPerformed

    private void btn_drive_thru_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_drive_thru_serviceActionPerformed
        
        JOptionPane.showMessageDialog(this, "Get your order from the drive thru corner 10 minutes after placing the order.","Drive thru service", JOptionPane.INFORMATION_MESSAGE); 
        JOptionPane.showMessageDialog(this, "Please note that, orders that are not accepted even after 3 hours of placing the order will be cancelled ","Drive thru service", JOptionPane.INFORMATION_MESSAGE);
        Order a4 = new Order();
        a4.txt_bill_id.setText(txt_bill_id.getText());
        a4.txt_order_type.setText("DriveThru");
        a4.txt_location.setText("DriveThruWindow");
        a4.setVisible(true);                      
        this.dispose();

    }//GEN-LAST:event_btn_drive_thru_serviceActionPerformed

    private void btn_dine_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dine_inActionPerformed
        
        CustomerTableNumber o = new CustomerTableNumber();
        o.txt_bill_id.setText(txt_bill_id.getText());
        o.txt_order_type.setText("DineIn");
        o.txt_reservation_fee.setText("0");
        o.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_dine_inActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // TODO add your handling code here: 
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_take_awayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_take_awayActionPerformed
        
        Order a4 = new Order();
        a4.txt_bill_id.setText(txt_bill_id.getText());
        a4.txt_order_type.setText("TakeAway");
        a4.txt_location.setText("Window");
        a4.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_take_awayActionPerformed
      
    private void btn_reservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservationsActionPerformed
   
        int response2 = JOptionPane.showConfirmDialog(this,"reservation valid only for next 12 hours. after 13 hours reservation will be canceled automatically. do you want to continue?" , "Update profile",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
        if(response2==JOptionPane.YES_OPTION)
        {

            CustomerTableNumber o = new CustomerTableNumber();
            o.txt_bill_id.setText(txt_bill_id.getText());
            o.txt_order_type.setText("Reservation");
            o.txt_reservation_fee.setText("200");
            o.setVisible(true);
            this.dispose();  
        
        }
        
        else if(response2==JOptionPane.NO_OPTION)
        {
            Start z = new Start();
            z.setVisible(true);
            this.dispose();  
        }
 
    }//GEN-LAST:event_btn_reservationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_customer_log_out_from_main;
    private javax.swing.JButton btn_dine_in;
    private javax.swing.JButton btn_drive_thru_service;
    private javax.swing.JButton btn_reservations;
    private javax.swing.JButton btn_take_away;
    private javax.swing.JButton btn_update_customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel redio_btn_dine_in;
    public javax.swing.JTextField txt_bill_id;
    // End of variables declaration//GEN-END:variables
}
