/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

import javax.swing.JOptionPane;
import java.sql.*;
import hevenly.Database.DatabaseConnector;
import java.util.regex.*; 
import hevenly.GUI.DatePicker;

/**
 *
 * @author MSii
 */
public class CustermerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form CustermerRegistration
     */
    public CustermerRegistration() {
        initComponents();
        
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_customer_gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_customer_register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_customer_first_name = new javax.swing.JTextField();
        txt_customer_lastname = new javax.swing.JTextField();
        txt_customer_emailaddress = new javax.swing.JTextField();
        txt_customer_phone_number = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo_gender = new javax.swing.JComboBox<>();
        txt_customer_phone_number1 = new javax.swing.JTextField();
        txt_customer_dob = new javax.swing.JTextField();
        btn_customer_first_name_clear = new javax.swing.JButton();
        btn_customer_last_name_clear = new javax.swing.JButton();
        btn_customer_calander = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_clear_customer_tp = new javax.swing.JButton();
        btn_support_service = new javax.swing.JButton();
        btn_log_out = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_customer_register.setBackground(new java.awt.Color(192, 168, 149));
        btn_customer_register.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_customer_register.setForeground(new java.awt.Color(67, 0, 0));
        btn_customer_register.setText("Register");
        btn_customer_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_registerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_customer_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 120, 30));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        txt_customer_first_name.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_customer_first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_customer_first_nameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_customer_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 140, -1));

        txt_customer_lastname.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_customer_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_customer_lastnameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_customer_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 140, -1));

        txt_customer_emailaddress.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jPanel1.add(txt_customer_emailaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 290, -1));

        txt_customer_phone_number.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_customer_phone_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_customer_phone_numberKeyPressed(evt);
            }
        });
        jPanel1.add(txt_customer_phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 140, -1));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("date of birth");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("This is your username");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        combo_gender.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "male", "female", "other" }));
        jPanel1.add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 140, 30));

        txt_customer_phone_number1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jPanel1.add(txt_customer_phone_number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 140, -1));

        txt_customer_dob.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jPanel1.add(txt_customer_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 150, 30));

        btn_customer_first_name_clear.setBackground(new java.awt.Color(255, 224, 212));
        btn_customer_first_name_clear.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_customer_first_name_clear.setText("clear");
        btn_customer_first_name_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_first_name_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_customer_first_name_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 70, 20));

        btn_customer_last_name_clear.setBackground(new java.awt.Color(255, 224, 212));
        btn_customer_last_name_clear.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_customer_last_name_clear.setText("clear");
        btn_customer_last_name_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_last_name_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_customer_last_name_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 70, 20));

        btn_customer_calander.setBackground(new java.awt.Color(255, 224, 212));
        btn_customer_calander.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_customer_calander.setText("select");
        btn_customer_calander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_calanderActionPerformed(evt);
            }
        });
        jPanel1.add(btn_customer_calander, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 80, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("yyyy-mm-dd");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        btn_clear_customer_tp.setBackground(new java.awt.Color(255, 224, 212));
        btn_clear_customer_tp.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_clear_customer_tp.setForeground(new java.awt.Color(95, 0, 0));
        btn_clear_customer_tp.setText("clear");
        btn_clear_customer_tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_customer_tpActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear_customer_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 70, 20));

        btn_support_service.setBackground(new java.awt.Color(192, 168, 149));
        btn_support_service.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_support_service.setForeground(new java.awt.Color(95, 0, 0));
        btn_support_service.setText("Support service-0771477627");
        btn_support_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_support_serviceActionPerformed(evt);
            }
        });
        jPanel1.add(btn_support_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_log_out.setBackground(new java.awt.Color(192, 168, 142));
        btn_log_out.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_log_out.setForeground(new java.awt.Color(95, 0, 0));
        btn_log_out.setText("Log out");
        btn_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_outActionPerformed(evt);
            }
        });
        jPanel1.add(btn_log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\login\\img_custermer.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con = null;
    PreparedStatement pst = null;
    
    //\\(?([0-9]{3})\\)?([ .-]?)([0-9]{3})\\2([0-9]{4})/
    public static boolean isValidPhone(String phone){  
        String phoneFormate ="^([+]\\d{2})?\\d{10}$";  
          
        Pattern p = Pattern.compile(phoneFormate);  
        if(phone == null){  
        return false;  
        }   
        return p.matcher(phone).matches();  
    }
    
    
    public static boolean isValidEmail(String email){  
        String emailFormate ="^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\."  
                + "[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$";  
          
        Pattern p = Pattern.compile(emailFormate);  
        if(email == null){  
        return false;  
        }   
        return p.matcher(email).matches();  
    }
      //(\\d(4))-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])
    public static boolean isValidDOB(String dob){  
        String dobFormate ="^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$";  
          
        Pattern p = Pattern.compile(dobFormate);  
        if(dob == null){  
        return false;  
        }   
        return p.matcher(dob).matches();  
    }
    
    private void btn_customer_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_registerActionPerformed
        if("".equals(txt_customer_first_name.getText()))
        {
         JOptionPane.showMessageDialog(this, "please enter first name","customer registration", JOptionPane.ERROR_MESSAGE); 
        }
        
        else if("".equals(txt_customer_lastname.getText()))
        {
         JOptionPane.showMessageDialog(this, "please enter last name","customer registration", JOptionPane.ERROR_MESSAGE); 
        }
        
        else if (isValidEmail(txt_customer_emailaddress.getText())== false){
        JOptionPane.showMessageDialog(this, "Enter valid Email","customer registration", JOptionPane.ERROR_MESSAGE); 
        txt_customer_emailaddress.setText("");
        }
        
        else if(isValidPhone(txt_customer_phone_number.getText()) == false)
        {
        JOptionPane.showMessageDialog(this, "Enter valid phone number","customer registration", JOptionPane.ERROR_MESSAGE); 
        txt_customer_phone_number.setText("");
        } 

        else if(combo_gender.getSelectedItem()=="select"){
         JOptionPane.showMessageDialog(this, "please select gender","customer registration", JOptionPane.ERROR_MESSAGE);    
        }
        
        else if (isValidDOB(txt_customer_dob.getText())== false){
        JOptionPane.showMessageDialog(this, "Enter valid date of birth in yyyy-mm-dd format","customer registration", JOptionPane.ERROR_MESSAGE); 
        txt_customer_dob.setText("");
        }
        
        else 
        {
        con = DatabaseConnector.connect();
        
        try{
        String q = "insert into customer values ('"+txt_customer_phone_number.getText()+"','"+txt_customer_first_name.getText()+"','"+txt_customer_lastname.getText()+"','"+txt_customer_emailaddress.getText()+"','"+combo_gender.getSelectedItem().toString()+"','"+txt_customer_dob.getText()+"')";
        pst  = con.prepareStatement(q);
        pst.execute();
        
        JOptionPane.showMessageDialog(this, "customer added succsessfuly","customer registration", JOptionPane.INFORMATION_MESSAGE); 
        JOptionPane.showMessageDialog(this, "enter your mobile number that you entered as a user name in your next login","customer registration", JOptionPane.INFORMATION_MESSAGE); 
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error","customer registration", JOptionPane.ERROR_MESSAGE); 
        
        int response = JOptionPane.showConfirmDialog(this,"Do you want to log out?" , "customer registration",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
            if(response==JOptionPane.YES_OPTION)
            { 
              this.dispose();
              Start a1= new Start();
              a1.setVisible(true);
            }
        
            else if(response==JOptionPane.NO_OPTION)
            {
              
              
            }
        }
 
        CustermerSignIn c = new CustermerSignIn();
        c.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btn_customer_registerActionPerformed

    private void txt_customer_first_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_customer_first_nameKeyPressed
        
        char c = evt.getKeyChar();

        if(Character.isLetter(c) ){
        txt_customer_first_name.setEditable(true);
        
        }
        else{
        txt_customer_first_name.setEditable(false);
        }
        
    }//GEN-LAST:event_txt_customer_first_nameKeyPressed

    private void txt_customer_lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_customer_lastnameKeyPressed
      
        char c = evt.getKeyChar();

        if(Character.isLetter(c) ){
        txt_customer_lastname.setEditable(true);
        }
        else{
        txt_customer_lastname.setEditable(false);
        }
        
    }//GEN-LAST:event_txt_customer_lastnameKeyPressed

    private void txt_customer_phone_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_customer_phone_numberKeyPressed
        
        char c = evt.getKeyChar();

        if(Character.isLetter(c) ){
        txt_customer_phone_number.setEditable(false);
        }
        else{
        txt_customer_phone_number.setEditable(true);
        }
    }//GEN-LAST:event_txt_customer_phone_numberKeyPressed

    private void btn_customer_first_name_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_first_name_clearActionPerformed
        
        txt_customer_first_name.setText("");
    }//GEN-LAST:event_btn_customer_first_name_clearActionPerformed

    private void btn_customer_last_name_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_last_name_clearActionPerformed
        
        txt_customer_lastname.setText("");
    }//GEN-LAST:event_btn_customer_last_name_clearActionPerformed

    private void btn_customer_calanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_calanderActionPerformed
        
        DatePicker datepicker = new DatePicker(this);
        txt_customer_dob.setText(datepicker.setPickedDate());
    }//GEN-LAST:event_btn_customer_calanderActionPerformed

    private void btn_clear_customer_tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_customer_tpActionPerformed
        txt_customer_phone_number.setText("");
    }//GEN-LAST:event_btn_clear_customer_tpActionPerformed

    private void btn_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_outActionPerformed
        Start t = new Start();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_log_outActionPerformed

    private void btn_support_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_support_serviceActionPerformed
        
    }//GEN-LAST:event_btn_support_serviceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustermerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustermerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustermerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustermerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustermerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear_customer_tp;
    private javax.swing.JButton btn_customer_calander;
    private javax.swing.JButton btn_customer_first_name_clear;
    private javax.swing.JButton btn_customer_last_name_clear;
    private javax.swing.JButton btn_customer_register;
    private javax.swing.JButton btn_log_out;
    private javax.swing.JButton btn_support_service;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.ButtonGroup grp_customer_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_customer_dob;
    private javax.swing.JTextField txt_customer_emailaddress;
    private javax.swing.JTextField txt_customer_first_name;
    private javax.swing.JTextField txt_customer_lastname;
    private javax.swing.JTextField txt_customer_phone_number;
    private javax.swing.JTextField txt_customer_phone_number1;
    // End of variables declaration//GEN-END:variables
}
