/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

import hevenly.Database.DatabaseConnector;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.*;

import java.util.Date;


/**
 *
 * @author MSii
 */

public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(190, 168, 149));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_complain = new javax.swing.JButton();
        btn_confirm_order = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        check_mocha = new javax.swing.JCheckBox();
        check_americano = new javax.swing.JCheckBox();
        check_latte = new javax.swing.JCheckBox();
        check_cappuccino = new javax.swing.JCheckBox();
        spinner_latte = new javax.swing.JSpinner();
        spinner_cappuccino = new javax.swing.JSpinner();
        spinner_americano = new javax.swing.JSpinner();
        spinner_mocha = new javax.swing.JSpinner();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        txt_mocha_price = new javax.swing.JTextField();
        txt_americano_price = new javax.swing.JTextField();
        txt_latte_price = new javax.swing.JTextField();
        btn_latte_add = new javax.swing.JButton();
        txt_cappuccino_price = new javax.swing.JTextField();
        btn_cappuccino_add = new javax.swing.JButton();
        btn_americano_add = new javax.swing.JButton();
        btn_mocha_add = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        check_chicken_sandwich = new javax.swing.JCheckBox();
        check_banana_woffles = new javax.swing.JCheckBox();
        check_egg_sandwich = new javax.swing.JCheckBox();
        check_chocolatte_woffles = new javax.swing.JCheckBox();
        spinner_chicken_sandwich = new javax.swing.JSpinner();
        spinner_egg_sandwich = new javax.swing.JSpinner();
        spinner_chocolatte_woffles = new javax.swing.JSpinner();
        spinner_banana_woffles = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        txt_chicken_sandwich_price = new javax.swing.JTextField();
        txt_egg_sandwich_price = new javax.swing.JTextField();
        txt_banana_woffles_price = new javax.swing.JTextField();
        txt_chocolatte_woffles_price = new javax.swing.JTextField();
        btn_chicken_sandwich_add = new javax.swing.JButton();
        btn_egg_sandwich_add = new javax.swing.JButton();
        btn_chocolatte_woffles_add = new javax.swing.JButton();
        btn_banana_woffles_add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        check_chocolatte_cake = new javax.swing.JCheckBox();
        check_coffee_cake = new javax.swing.JCheckBox();
        check_strawberry_cake = new javax.swing.JCheckBox();
        check_vanila_cake = new javax.swing.JCheckBox();
        spinner_vanila_cake = new javax.swing.JSpinner();
        spinner_chocolatte_cake = new javax.swing.JSpinner();
        spinner_coffee_cake = new javax.swing.JSpinner();
        spinner_strawberry_cake = new javax.swing.JSpinner();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        txt_vanila_cake_price = new javax.swing.JTextField();
        txt_chocolatte_cake_price = new javax.swing.JTextField();
        txt_strawberry_cake_price = new javax.swing.JTextField();
        txt_coffee_cake_price = new javax.swing.JTextField();
        btn_vanila_cake_add = new javax.swing.JButton();
        btn_chocolatte_cake_add = new javax.swing.JButton();
        add_strawberry_cake_add = new javax.swing.JButton();
        add_coffee_cake_add = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        check_milk_tea = new javax.swing.JCheckBox();
        check_hot_chocolatte = new javax.swing.JCheckBox();
        check_masala_tea = new javax.swing.JCheckBox();
        check_apple_juice = new javax.swing.JCheckBox();
        spinner_masala_tea = new javax.swing.JSpinner();
        spinner_milk_tea = new javax.swing.JSpinner();
        spinner_apple_juice = new javax.swing.JSpinner();
        spinner_hot_chocolatte = new javax.swing.JSpinner();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        txt_masala_tea_price = new javax.swing.JTextField();
        txt_apple_juice_price = new javax.swing.JTextField();
        btn_apple_juice_add = new javax.swing.JButton();
        btn_hot_chocolatte_add = new javax.swing.JButton();
        btn_milk_tea_add = new javax.swing.JButton();
        btn_masala_tea_add = new javax.swing.JButton();
        txt_hot_chocolatte_price = new javax.swing.JTextField();
        txt_milk_tea_price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_bill = new javax.swing.JTable();
        txt_bill_total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_bill = new javax.swing.JTextArea();
        txt_bill_id = new javax.swing.JTextField();
        txt_order_type = new javax.swing.JTextField();
        txt_reservation_fee = new javax.swing.JTextField();
        txt_location = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_complain.setBackground(new java.awt.Color(192, 168, 142));
        btn_complain.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_complain.setForeground(new java.awt.Color(95, 0, 0));
        btn_complain.setText("I have a complain");
        btn_complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_complainActionPerformed(evt);
            }
        });
        getContentPane().add(btn_complain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_confirm_order.setBackground(new java.awt.Color(207, 177, 160));
        btn_confirm_order.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        btn_confirm_order.setForeground(new java.awt.Color(71, 0, 0));
        btn_confirm_order.setText("Confirm Order");
        btn_confirm_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirm_orderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirm_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 165, 30));

        jTabbedPane1.setBackground(new java.awt.Color(209, 181, 165));
        jTabbedPane1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(236, 227, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_mocha.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_mocha.setForeground(new java.awt.Color(48, 33, 24));
        check_mocha.setText("mocha");
        jPanel2.add(check_mocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 256, 176, -1));

        check_americano.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_americano.setForeground(new java.awt.Color(48, 33, 24));
        check_americano.setText("Americano");
        jPanel2.add(check_americano, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 178, 176, -1));

        check_latte.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_latte.setForeground(new java.awt.Color(48, 33, 24));
        check_latte.setText("latte");
        jPanel2.add(check_latte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        check_cappuccino.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_cappuccino.setForeground(new java.awt.Color(48, 33, 24));
        check_cappuccino.setText("cappuccino");
        jPanel2.add(check_cappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 100, 176, -1));

        spinner_latte.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel2.add(spinner_latte, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 41, -1, -1));

        spinner_cappuccino.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel2.add(spinner_cappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 109, -1, -1));

        spinner_americano.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel2.add(spinner_americano, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 187, -1, -1));

        spinner_mocha.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel2.add(spinner_mocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 265, -1, -1));

        jLabel73.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel73.setText("Rs");
        jPanel2.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel74.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel74.setText("Rs");
        jPanel2.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel75.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel75.setText("Rs");
        jPanel2.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel76.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel76.setText("Rs");
        jPanel2.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        txt_mocha_price.setEditable(false);
        txt_mocha_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_mocha_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_mocha_price.setText("400");
        jPanel2.add(txt_mocha_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        txt_americano_price.setEditable(false);
        txt_americano_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_americano_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_americano_price.setText("300");
        jPanel2.add(txt_americano_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        txt_latte_price.setEditable(false);
        txt_latte_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_latte_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_latte_price.setText("400");
        jPanel2.add(txt_latte_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        btn_latte_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_latte_add.setText("Add");
        btn_latte_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_latte_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_latte_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        txt_cappuccino_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_cappuccino_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_cappuccino_price.setText("500");
        jPanel2.add(txt_cappuccino_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        btn_cappuccino_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_cappuccino_add.setText("Add");
        btn_cappuccino_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cappuccino_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cappuccino_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        btn_americano_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_americano_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_americano_add.setText("Add");
        btn_americano_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_americano_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_americano_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        btn_mocha_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_mocha_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_mocha_add.setText("Add");
        btn_mocha_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mocha_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mocha_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jTabbedPane1.addTab("coffees", jPanel2);

        jPanel1.setBackground(new java.awt.Color(237, 226, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_chicken_sandwich.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        check_chicken_sandwich.setForeground(new java.awt.Color(48, 33, 24));
        check_chicken_sandwich.setText("chicken");
        jPanel1.add(check_chicken_sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 89, 109, -1));

        check_banana_woffles.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        check_banana_woffles.setForeground(new java.awt.Color(48, 33, 24));
        check_banana_woffles.setText("banana&honey");
        jPanel1.add(check_banana_woffles, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 242, 154, -1));

        check_egg_sandwich.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        check_egg_sandwich.setForeground(new java.awt.Color(48, 33, 24));
        check_egg_sandwich.setText("egg");
        jPanel1.add(check_egg_sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 134, 94, -1));

        check_chocolatte_woffles.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        check_chocolatte_woffles.setForeground(new java.awt.Color(48, 33, 24));
        check_chocolatte_woffles.setText("chocolatte");
        jPanel1.add(check_chocolatte_woffles, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 286, 120, 26));

        spinner_chicken_sandwich.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel1.add(spinner_chicken_sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 90, -1, -1));

        spinner_egg_sandwich.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel1.add(spinner_egg_sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 135, -1, -1));

        spinner_chocolatte_woffles.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel1.add(spinner_chocolatte_woffles, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        spinner_banana_woffles.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel1.add(spinner_banana_woffles, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel2.setText("woffles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 191, 131, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel3.setText("sandwich");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 38, 131, -1));

        jLabel85.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel85.setText("Rs");
        jPanel1.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 20, -1));

        jLabel86.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel86.setText("Rs");
        jPanel1.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 20, -1));

        jLabel87.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel87.setText("Rs");
        jPanel1.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 20, -1));

        jLabel88.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel88.setText("Rs");
        jPanel1.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 20, -1));

        txt_chicken_sandwich_price.setEditable(false);
        txt_chicken_sandwich_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_chicken_sandwich_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_chicken_sandwich_price.setText("300");
        jPanel1.add(txt_chicken_sandwich_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        txt_egg_sandwich_price.setEditable(false);
        txt_egg_sandwich_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_egg_sandwich_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_egg_sandwich_price.setText("200");
        jPanel1.add(txt_egg_sandwich_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        txt_banana_woffles_price.setEditable(false);
        txt_banana_woffles_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_banana_woffles_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_banana_woffles_price.setText("200");
        jPanel1.add(txt_banana_woffles_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        txt_chocolatte_woffles_price.setEditable(false);
        txt_chocolatte_woffles_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_chocolatte_woffles_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_chocolatte_woffles_price.setText("200");
        jPanel1.add(txt_chocolatte_woffles_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        btn_chicken_sandwich_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_chicken_sandwich_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_chicken_sandwich_add.setText("Add");
        btn_chicken_sandwich_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chicken_sandwich_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chicken_sandwich_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        btn_egg_sandwich_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_egg_sandwich_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_egg_sandwich_add.setText("Add");
        btn_egg_sandwich_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_egg_sandwich_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_egg_sandwich_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        btn_chocolatte_woffles_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_chocolatte_woffles_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_chocolatte_woffles_add.setText("Add");
        btn_chocolatte_woffles_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chocolatte_woffles_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chocolatte_woffles_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        btn_banana_woffles_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_banana_woffles_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_banana_woffles_add.setText("Add");
        btn_banana_woffles_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_banana_woffles_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_banana_woffles_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jTabbedPane1.addTab("breakfast", jPanel1);

        jPanel3.setBackground(new java.awt.Color(236, 227, 219));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_chocolatte_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_chocolatte_cake.setForeground(new java.awt.Color(48, 33, 24));
        check_chocolatte_cake.setText("chocolatte");
        jPanel3.add(check_chocolatte_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 99, 176, -1));

        check_coffee_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_coffee_cake.setForeground(new java.awt.Color(48, 33, 24));
        check_coffee_cake.setText("coffee");
        jPanel3.add(check_coffee_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 243, 176, -1));

        check_strawberry_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_strawberry_cake.setForeground(new java.awt.Color(48, 33, 24));
        check_strawberry_cake.setText("strawberry");
        jPanel3.add(check_strawberry_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 168, 176, -1));

        check_vanila_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_vanila_cake.setForeground(new java.awt.Color(48, 33, 24));
        check_vanila_cake.setText("vanila");
        jPanel3.add(check_vanila_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 30, 176, -1));

        spinner_vanila_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel3.add(spinner_vanila_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 39, -1, -1));

        spinner_chocolatte_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel3.add(spinner_chocolatte_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 108, -1, -1));

        spinner_coffee_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel3.add(spinner_coffee_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        spinner_strawberry_cake.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel3.add(spinner_strawberry_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 177, -1, -1));

        jLabel77.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel77.setText("Rs");
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel78.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel78.setText("Rs");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel79.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel79.setText("Rs");
        jPanel3.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel80.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel80.setText("Rs");
        jPanel3.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        txt_vanila_cake_price.setEditable(false);
        txt_vanila_cake_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_vanila_cake_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_vanila_cake_price.setText("150");
        jPanel3.add(txt_vanila_cake_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        txt_chocolatte_cake_price.setEditable(false);
        txt_chocolatte_cake_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_chocolatte_cake_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_chocolatte_cake_price.setText("180");
        jPanel3.add(txt_chocolatte_cake_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        txt_strawberry_cake_price.setEditable(false);
        txt_strawberry_cake_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_strawberry_cake_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_strawberry_cake_price.setText("160");
        jPanel3.add(txt_strawberry_cake_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        txt_coffee_cake_price.setEditable(false);
        txt_coffee_cake_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_coffee_cake_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_coffee_cake_price.setText("170");
        jPanel3.add(txt_coffee_cake_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        btn_vanila_cake_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_vanila_cake_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_vanila_cake_add.setText("Add");
        btn_vanila_cake_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vanila_cake_addActionPerformed(evt);
            }
        });
        jPanel3.add(btn_vanila_cake_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        btn_chocolatte_cake_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_chocolatte_cake_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_chocolatte_cake_add.setText("Add");
        btn_chocolatte_cake_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chocolatte_cake_addActionPerformed(evt);
            }
        });
        jPanel3.add(btn_chocolatte_cake_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        add_strawberry_cake_add.setBackground(new java.awt.Color(192, 168, 149));
        add_strawberry_cake_add.setForeground(new java.awt.Color(95, 0, 0));
        add_strawberry_cake_add.setText("Add");
        add_strawberry_cake_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_strawberry_cake_addActionPerformed(evt);
            }
        });
        jPanel3.add(add_strawberry_cake_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        add_coffee_cake_add.setBackground(new java.awt.Color(192, 168, 149));
        add_coffee_cake_add.setForeground(new java.awt.Color(95, 0, 0));
        add_coffee_cake_add.setText("Add");
        add_coffee_cake_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_coffee_cake_addActionPerformed(evt);
            }
        });
        jPanel3.add(add_coffee_cake_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jTabbedPane1.addTab("cakes", jPanel3);

        jPanel4.setBackground(new java.awt.Color(236, 227, 219));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_milk_tea.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_milk_tea.setForeground(new java.awt.Color(48, 33, 24));
        check_milk_tea.setText("milk tea");
        jPanel4.add(check_milk_tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 176, -1));

        check_hot_chocolatte.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_hot_chocolatte.setForeground(new java.awt.Color(48, 33, 24));
        check_hot_chocolatte.setText("hot chocalatte");
        jPanel4.add(check_hot_chocolatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        check_masala_tea.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_masala_tea.setForeground(new java.awt.Color(48, 33, 24));
        check_masala_tea.setText("masala tea");
        jPanel4.add(check_masala_tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 31, 176, -1));

        check_apple_juice.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        check_apple_juice.setForeground(new java.awt.Color(48, 33, 24));
        check_apple_juice.setText("apple juice");
        jPanel4.add(check_apple_juice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, -1));

        spinner_masala_tea.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel4.add(spinner_masala_tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        spinner_milk_tea.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel4.add(spinner_milk_tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        spinner_apple_juice.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel4.add(spinner_apple_juice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        spinner_hot_chocolatte.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jPanel4.add(spinner_hot_chocolatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel81.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel81.setText("Rs");
        jPanel4.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 20, -1));

        jLabel82.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel82.setText("Rs");
        jPanel4.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 20, -1));

        jLabel83.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel83.setText("Rs");
        jPanel4.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 20, -1));

        jLabel84.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel84.setText("Rs");
        jPanel4.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 20, -1));

        txt_masala_tea_price.setEditable(false);
        txt_masala_tea_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_masala_tea_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_masala_tea_price.setText("250");
        jPanel4.add(txt_masala_tea_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        txt_apple_juice_price.setEditable(false);
        txt_apple_juice_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_apple_juice_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_apple_juice_price.setText("300");
        jPanel4.add(txt_apple_juice_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        btn_apple_juice_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_apple_juice_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_apple_juice_add.setText("Add");
        btn_apple_juice_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apple_juice_addActionPerformed(evt);
            }
        });
        jPanel4.add(btn_apple_juice_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        btn_hot_chocolatte_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_hot_chocolatte_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_hot_chocolatte_add.setText("Add");
        btn_hot_chocolatte_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hot_chocolatte_addActionPerformed(evt);
            }
        });
        jPanel4.add(btn_hot_chocolatte_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        btn_milk_tea_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_milk_tea_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_milk_tea_add.setText("Add");
        btn_milk_tea_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_milk_tea_addActionPerformed(evt);
            }
        });
        jPanel4.add(btn_milk_tea_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        btn_masala_tea_add.setBackground(new java.awt.Color(192, 168, 149));
        btn_masala_tea_add.setForeground(new java.awt.Color(95, 0, 0));
        btn_masala_tea_add.setText("Add");
        btn_masala_tea_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masala_tea_addActionPerformed(evt);
            }
        });
        jPanel4.add(btn_masala_tea_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        txt_hot_chocolatte_price.setEditable(false);
        txt_hot_chocolatte_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_hot_chocolatte_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_hot_chocolatte_price.setText("250");
        jPanel4.add(txt_hot_chocolatte_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        txt_milk_tea_price.setEditable(false);
        txt_milk_tea_price.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txt_milk_tea_price.setForeground(new java.awt.Color(95, 0, 0));
        txt_milk_tea_price.setText("250");
        jPanel4.add(txt_milk_tea_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jTabbedPane1.addTab("bevarages", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 499, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hevenly/6ug3jw.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 268, 113));

        jLabel52.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel52.setText("300");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 231, 37, 0));

        jLabel53.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel53.setText("300");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 241, 37, 0));

        jLabel54.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel54.setText("300");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 251, 37, 0));

        table_bill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item id", "item name", "item quantity", "item price"
            }
        ));
        jScrollPane1.setViewportView(table_bill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 320, 180));

        txt_bill_total.setEditable(false);
        getContentPane().add(txt_bill_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 180, 70, 30));

        txt_bill.setColumns(20);
        txt_bill.setRows(5);
        jScrollPane2.setViewportView(txt_bill);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 360, 320));

        txt_bill_id.setEditable(false);
        getContentPane().add(txt_bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        txt_order_type.setEditable(false);
        getContentPane().add(txt_order_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        txt_reservation_fee.setEditable(false);
        txt_reservation_fee.setText("0");
        getContentPane().add(txt_reservation_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, -1, -1));

        txt_location.setEditable(false);
        getContentPane().add(txt_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jLabel20.setText("order type");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel21.setText("bill id");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel22.setText("location");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel23.setText("Total Rs");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, -1, -1));

        jLabel24.setText("reservation fee Rs");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, -1, -1));

        btn_delete.setBackground(new java.awt.Color(207, 177, 160));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Connection con = null;
        
        PreparedStatement pst = null;
        
        
    
    private void btn_complainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_complainActionPerformed
 
        
        Complain r = new Complain();
        r.setVisible(true);
    }//GEN-LAST:event_btn_complainActionPerformed

    private void btn_confirm_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirm_orderActionPerformed
         DefaultTableModel dff = (DefaultTableModel) table_bill.getModel();
        if (dff.getRowCount()==0){
           JOptionPane.showMessageDialog(this, "please select your order first","empty order", JOptionPane.ERROR_MESSAGE);
           }
        else{
        try{
           con = DatabaseConnector.connect();
           for (int i = 0; i < table_bill.getRowCount(); i++) 
            {    
                String Name = dff.getValueAt(i, 1).toString();
                String Qty = dff.getValueAt(i, 2).toString();
                String Price = dff.getValueAt(i, 3).toString();
                String s3 = "insert into billitems (bill_id,item,quatity,price)values ('"+txt_bill_id.getText()+"','"+Name+"','"+Qty+"','"+Price+"')"; 
            
                pst  = con.prepareStatement(s3);           
                pst.execute();
        
            
            }
        
        JOptionPane.showMessageDialog(this, "order entered! ","order", JOptionPane.INFORMATION_MESSAGE); 
        JOptionPane.showMessageDialog(this, "your bill number is"+txt_bill_id.getText(),"order", JOptionPane.INFORMATION_MESSAGE); 
        JOptionPane.showMessageDialog(this, "your location is"+txt_location.getText(),"order", JOptionPane.INFORMATION_MESSAGE); 
                
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(this, "Error","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try{
        con = DatabaseConnector.connect();
        String q = "update bill set location ='"+txt_location.getText()+"' where bill_id='"+txt_bill_id.getText()+"'";
        String r = "update bill set type ='"+txt_order_type.getText()+"' where bill_id='"+txt_bill_id.getText()+"'";
        String s = "update bill set amount ='"+txt_bill_total.getText()+"' where bill_id='"+txt_bill_id.getText()+"'";
        String t = "update bill set reservation_fee ='"+txt_reservation_fee.getText()+"' where bill_id='"+txt_bill_id.getText()+"'";
        
           
        pst  = con.prepareStatement(q);
        pst.execute();
        
        pst  = con.prepareStatement(r);
        pst.execute();
        
        pst  = con.prepareStatement(s);
        pst.execute();
        
        pst  = con.prepareStatement(t);
        pst.execute();
        
        Date u = new Date();
        java.sql.Date v = new java.sql.Date(u.getTime());
        String w = "update bill set date ='"+v+"' where bill_id='"+txt_bill_id.getText()+"'";
        
        pst  = con.prepareStatement(w);
        pst.execute();
        
        java.sql.Time y = new java.sql.Time(u.getTime());
        String z = "update bill set time ='"+y+"' where bill_id='"+txt_bill_id.getText()+"'";
        
        pst  = con.prepareStatement(z);
        pst.execute();
        
        this.setVisible(false);
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, " Try again or contact our staff","Error", JOptionPane.ERROR_MESSAGE); 
        
        int response = JOptionPane.showConfirmDialog(this,"Do you want to log out?" , "Error",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
            if(response==JOptionPane.YES_OPTION)
            { 
              this.dispose();
              Start a1= new Start();
              a1.setVisible(true);
            }
        
            else if(response==JOptionPane.NO_OPTION)
            {
              
              
            }
        }
        
        try {
           
           Date u1 = new Date();
           java.sql.Date v1 = new java.sql.Date(u1.getTime());            
           java.sql.Time y1 = new java.sql.Time(u1.getTime());
           txt_bill.setText(txt_bill.getText() + "                                    Heavenly\n");
           txt_bill.setText(txt_bill.getText() + "date : " + v1 +"\n");
           txt_bill.setText(txt_bill.getText() + "time : " + y1 +"\n");
           txt_bill.setText(txt_bill.getText() + "                                    Bill\n");
           txt_bill.setText(txt_bill.getText() + "bill id : " + txt_bill_id.getText() +"\n");
           txt_bill.setText(txt_bill.getText() + "order type : " + txt_order_type.getText() +"\n");
           txt_bill.setText(txt_bill.getText() + "location : " + txt_location.getText() +"\n");
           txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------\n");
           txt_bill.setText(txt_bill.getText() + "  Item \tQty \tPrice" +"\n");
           txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------\n");
            
            
           // get table Product details
           DefaultTableModel df = (DefaultTableModel) table_bill.getModel();
           for (int i = 0; i < table_bill.getRowCount(); i++) 
            {    
                String Name = df.getValueAt(i, 1).toString();
                String Qty = df.getValueAt(i, 2).toString();
                String Price = df.getValueAt(i, 3).toString();

                txt_bill.setText(txt_bill.getText() +"  "+ Name+"\t"+Qty +"\t"+Price + "\n");
            }
            
           txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------\n");
           txt_bill.setText(txt_bill.getText() + "Reservation fee  : " + txt_reservation_fee.getText() +"\n");           
           txt_bill.setText(txt_bill.getText() + "Sub Total : " + txt_bill_total.getText() +"\n");                                             
           txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------\n");
           txt_bill.setText(txt_bill.getText() + "Thank you come again"+"\n\n\n");
           txt_bill.setText(txt_bill.getText() + "                          software by # (Hashini Fernando)"+"\n");

           JOptionPane.showMessageDialog(this, "next step is print the bill so, please enter print command and give your order number and save it!.Then you can get your printed biil. in any issue cantact us 0771477627. your order number is "+txt_bill_id.getText(),"order", JOptionPane.INFORMATION_MESSAGE); 
           txt_bill.print(); //print
           
           JOptionPane.showMessageDialog(this, "log out only end of the service. if not your table will be available for other customers. this does not apply to the drive thru and take away services ","order", JOptionPane.INFORMATION_MESSAGE); 
           Rate c1 = new Rate();
           c1.txt_location.setText(txt_location.getText());
           c1.txt_bill_id.setText(txt_bill_id.getText());
           
           c1.setVisible(true);
           }
           catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error","Error", JOptionPane.ERROR_MESSAGE);    
           }

        }
    }//GEN-LAST:event_btn_confirm_orderActionPerformed

    private void btn_latte_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_latte_addActionPerformed
       int i =(int) spinner_latte.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_latte_price.getText());
       addtables(1,"latte",i,j);
       cal();
       }
    }//GEN-LAST:event_btn_latte_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
      DefaultTableModel dt = (DefaultTableModel) table_bill.getModel();         
      int rw = table_bill.getSelectedRow();
      dt.removeRow(rw);       
      cal();  //re calculate
          
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_cappuccino_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cappuccino_addActionPerformed
       int i =(int) spinner_cappuccino.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_cappuccino_price.getText());
       addtables(2,"cappuccino",i,j);
       cal();
       }
    }//GEN-LAST:event_btn_cappuccino_addActionPerformed

    private void btn_americano_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_americano_addActionPerformed
       int i =(int) spinner_americano.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_americano_price.getText());
       addtables(3,"americano",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_americano_addActionPerformed

    private void btn_mocha_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mocha_addActionPerformed
       int i =(int) spinner_mocha.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_mocha_price.getText());
       addtables(4,"mocha",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_mocha_addActionPerformed

    private void btn_chicken_sandwich_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chicken_sandwich_addActionPerformed
       int i =(int) spinner_chicken_sandwich.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_chicken_sandwich_price.getText());
       addtables(5,"chicken_sandwich",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_chicken_sandwich_addActionPerformed

    private void btn_egg_sandwich_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_egg_sandwich_addActionPerformed
       int i =(int) spinner_egg_sandwich.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_egg_sandwich_price.getText());
       addtables(6,"egg_sandwich",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_egg_sandwich_addActionPerformed

    private void btn_banana_woffles_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banana_woffles_addActionPerformed
       int i =(int) spinner_banana_woffles.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_banana_woffles_price.getText());
       addtables(7,"banana_woffles",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_banana_woffles_addActionPerformed

    private void btn_chocolatte_woffles_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chocolatte_woffles_addActionPerformed
       int i =(int) spinner_chocolatte_woffles.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_chocolatte_woffles_price.getText());
       addtables(8,"chocolatte_woffles",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_chocolatte_woffles_addActionPerformed

    private void btn_vanila_cake_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vanila_cake_addActionPerformed
       int i =(int) spinner_vanila_cake.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_vanila_cake_price.getText());
       addtables(9,"vanila_cake",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_vanila_cake_addActionPerformed

    private void btn_chocolatte_cake_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chocolatte_cake_addActionPerformed
       int i =(int) spinner_chocolatte_cake.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_chocolatte_cake_price.getText());
       addtables(10,"chocolatte_cake",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_chocolatte_cake_addActionPerformed

    private void add_strawberry_cake_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_strawberry_cake_addActionPerformed
       int i =(int) spinner_strawberry_cake.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_strawberry_cake_price.getText());
       addtables(11,"strawberry_cake",i,j);
       cal();
       } 
    }//GEN-LAST:event_add_strawberry_cake_addActionPerformed

    private void add_coffee_cake_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_coffee_cake_addActionPerformed
       int i =(int) spinner_coffee_cake.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_coffee_cake_price.getText());
       addtables(12,"coffee_cake",i,j);
       cal();
       } 
    }//GEN-LAST:event_add_coffee_cake_addActionPerformed

    private void btn_masala_tea_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masala_tea_addActionPerformed
       int i =(int) spinner_masala_tea.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_masala_tea_price.getText());
       addtables(13,"masala_tea",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_masala_tea_addActionPerformed

    private void btn_milk_tea_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_milk_tea_addActionPerformed
       int i =(int) spinner_milk_tea.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_milk_tea_price.getText());
       addtables(14,"milk_tea",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_milk_tea_addActionPerformed

    private void btn_hot_chocolatte_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hot_chocolatte_addActionPerformed
       int i =(int) spinner_hot_chocolatte.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }      
       else{
       double j = Double.parseDouble(txt_hot_chocolatte_price.getText());
       addtables(15,"chocolatte",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_hot_chocolatte_addActionPerformed

    private void btn_apple_juice_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apple_juice_addActionPerformed
       int i =(int) spinner_apple_juice.getValue();
       if(i<=0){
       JOptionPane.showMessageDialog(this, "invalid order","order", JOptionPane.ERROR_MESSAGE); 
       }
       else{
       double j = Double.parseDouble(txt_apple_juice_price.getText());
       addtables(16,"apple_juice",i,j);
       cal();
       } 
    }//GEN-LAST:event_btn_apple_juice_addActionPerformed

    
public void addtables(int id ,String Name,int Qty ,Double Price){    
        DefaultTableModel dt = (DefaultTableModel) table_bill.getModel();
        
        DecimalFormat df = new DecimalFormat("00.00") ;       
        double totPrice = Price * Double.valueOf(Qty) ;       
        String TotalPrice = df.format(totPrice);
        
        Vector v = new Vector();       
        v.add(id);
        v.add(Name);
        v.add(Qty);
        v.add(TotalPrice); // total price
        
        dt.addRow(v);
    }

public void cal(){
        //cal total table values  
        int numOfRow = table_bill.getRowCount() ;
        double tot = 0.0 ;
   
        for (int i = 0; i < numOfRow; i++)
        {           
           double value = Double.parseDouble(table_bill.getValueAt(i, 3).toString());         
           tot += value ;
        }
        
        double z= Double.parseDouble(txt_reservation_fee.getText());
        tot +=z;
        DecimalFormat df = new DecimalFormat("00.00") ;
        txt_bill_total.setText(df.format(tot));
   } 
    
       
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_coffee_cake_add;
    private javax.swing.JButton add_strawberry_cake_add;
    private javax.swing.JButton btn_americano_add;
    private javax.swing.JButton btn_apple_juice_add;
    private javax.swing.JButton btn_banana_woffles_add;
    private javax.swing.JButton btn_cappuccino_add;
    private javax.swing.JButton btn_chicken_sandwich_add;
    private javax.swing.JButton btn_chocolatte_cake_add;
    private javax.swing.JButton btn_chocolatte_woffles_add;
    private javax.swing.JButton btn_complain;
    private javax.swing.JButton btn_confirm_order;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_egg_sandwich_add;
    private javax.swing.JButton btn_hot_chocolatte_add;
    private javax.swing.JButton btn_latte_add;
    private javax.swing.JButton btn_masala_tea_add;
    private javax.swing.JButton btn_milk_tea_add;
    private javax.swing.JButton btn_mocha_add;
    private javax.swing.JButton btn_vanila_cake_add;
    private javax.swing.JCheckBox check_americano;
    private javax.swing.JCheckBox check_apple_juice;
    private javax.swing.JCheckBox check_banana_woffles;
    private javax.swing.JCheckBox check_cappuccino;
    private javax.swing.JCheckBox check_chicken_sandwich;
    private javax.swing.JCheckBox check_chocolatte_cake;
    private javax.swing.JCheckBox check_chocolatte_woffles;
    private javax.swing.JCheckBox check_coffee_cake;
    private javax.swing.JCheckBox check_egg_sandwich;
    private javax.swing.JCheckBox check_hot_chocolatte;
    private javax.swing.JCheckBox check_latte;
    private javax.swing.JCheckBox check_masala_tea;
    private javax.swing.JCheckBox check_milk_tea;
    private javax.swing.JCheckBox check_mocha;
    private javax.swing.JCheckBox check_strawberry_cake;
    private javax.swing.JCheckBox check_vanila_cake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spinner_americano;
    private javax.swing.JSpinner spinner_apple_juice;
    private javax.swing.JSpinner spinner_banana_woffles;
    private javax.swing.JSpinner spinner_cappuccino;
    private javax.swing.JSpinner spinner_chicken_sandwich;
    private javax.swing.JSpinner spinner_chocolatte_cake;
    private javax.swing.JSpinner spinner_chocolatte_woffles;
    private javax.swing.JSpinner spinner_coffee_cake;
    private javax.swing.JSpinner spinner_egg_sandwich;
    private javax.swing.JSpinner spinner_hot_chocolatte;
    private javax.swing.JSpinner spinner_latte;
    private javax.swing.JSpinner spinner_masala_tea;
    private javax.swing.JSpinner spinner_milk_tea;
    private javax.swing.JSpinner spinner_mocha;
    private javax.swing.JSpinner spinner_strawberry_cake;
    private javax.swing.JSpinner spinner_vanila_cake;
    private javax.swing.JTable table_bill;
    private javax.swing.JTextField txt_americano_price;
    private javax.swing.JTextField txt_apple_juice_price;
    private javax.swing.JTextField txt_banana_woffles_price;
    private javax.swing.JTextArea txt_bill;
    public javax.swing.JTextField txt_bill_id;
    private javax.swing.JTextField txt_bill_total;
    private javax.swing.JTextField txt_cappuccino_price;
    private javax.swing.JTextField txt_chicken_sandwich_price;
    private javax.swing.JTextField txt_chocolatte_cake_price;
    private javax.swing.JTextField txt_chocolatte_woffles_price;
    private javax.swing.JTextField txt_coffee_cake_price;
    private javax.swing.JTextField txt_egg_sandwich_price;
    private javax.swing.JTextField txt_hot_chocolatte_price;
    private javax.swing.JTextField txt_latte_price;
    public javax.swing.JTextField txt_location;
    private javax.swing.JTextField txt_masala_tea_price;
    private javax.swing.JTextField txt_milk_tea_price;
    private javax.swing.JTextField txt_mocha_price;
    public javax.swing.JTextField txt_order_type;
    public javax.swing.JTextField txt_reservation_fee;
    private javax.swing.JTextField txt_strawberry_cake_price;
    private javax.swing.JTextField txt_vanila_cake_price;
    // End of variables declaration//GEN-END:variables
}
