/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hevenly;

/**
 *
 * @author MSii
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(190, 168, 149));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_customer_registration = new javax.swing.JButton();
        btn_customer_login = new javax.swing.JButton();
        btn_employee_login = new javax.swing.JButton();
        btn_manager_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(111, 78, 55));
        setForeground(new java.awt.Color(102, 51, 0));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_customer_registration.setBackground(new java.awt.Color(255, 224, 212));
        btn_customer_registration.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btn_customer_registration.setText(" Make a customer account");
        btn_customer_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_registrationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customer_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, 90));

        btn_customer_login.setBackground(new java.awt.Color(255, 224, 212));
        btn_customer_login.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        btn_customer_login.setText("Customer Login");
        btn_customer_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customer_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 200, 90));

        btn_employee_login.setBackground(new java.awt.Color(255, 224, 212));
        btn_employee_login.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        btn_employee_login.setText("Complain Box");
        btn_employee_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employee_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_employee_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 200, 90));

        btn_manager_login.setBackground(new java.awt.Color(255, 224, 212));
        btn_manager_login.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        btn_manager_login.setText("Manager Login");
        btn_manager_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manager_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_manager_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 200, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSii\\Desktop\\EADCW\\start\\img_shop.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_customer_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_registrationActionPerformed
       
        CustermerRegistration a = new CustermerRegistration();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_customer_registrationActionPerformed

    private void btn_customer_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_loginActionPerformed
      
        CustermerSignIn b = new CustermerSignIn();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_customer_loginActionPerformed

    private void btn_employee_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employee_loginActionPerformed
       
        Complain e = new Complain();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_employee_loginActionPerformed

    private void btn_manager_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manager_loginActionPerformed
     
        ManagerSignIn g = new ManagerSignIn();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manager_loginActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
                
            }

           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_customer_login;
    private javax.swing.JButton btn_customer_registration;
    private javax.swing.JButton btn_employee_login;
    private javax.swing.JButton btn_manager_login;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
